### ISSUE TITLE
get signals for each basecall

### ISSUE THREAD

**Issue by hsinnan75** [ktan8/nanopore_telomere_basecall#4]
Hi, I was wondering how you get signals for each basecall. To the best of my knowledge, each basecall contains variable number of signals. How do you compare two 6-mers with different numbers of signals. Could you show me how you get the signals of each basecall. Thank you very much.

**Comment by ktan8** [comment]
Hi hsinnan75, 

You're right to say that different number of timeframes/signals give rise to each basecall since the rate at which the DNA molecule moves through the nanopore can vary to some degree. Nonetheless, even though the DNA molecule can move through the nanopore at different rate, the mean current value observed for each 6-mer tends to be reasonably consistent. This was the result published by Oxford Nanopore previously (https://github.com/nanoporetech/kmer_models).

We therefore used these k-mer models published by Oxford Nanopore to predict what the corresponding current profile for a telomeric repeat should look like. Specifically, this is done by plotting out the current values of the circular permutations of the telomeric repeat (i.e. TTAGGG, TAGGGT, AGGGTT, etc.). For a full description, you can also refer to our preprint at https://www.biorxiv.org/content/10.1101/2022.01.11.475254v1.full

Hope this is helpful.

- KT

**Comment by ktan8** [comment]
Replied and resolved
